# Generated by Django 5.0.6 on 2024-07-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time_to_finish',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
