# Generated by Django 5.0.6 on 2024-07-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_project_time_to_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time_to_finish',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
